Create table Funcionarios(
FuncionarioID int primary key,
Matricula int ,
Nome nvarchar(100)  null,
Cpf nvarchar(20) null,
Nasc nvarchar(20) null,
Email nvarchar(100)  null,
Rg nvarchar(20)   null,
Estadocivil nvarchar(100)  null,
Sexo nvarchar(100)  null,
Filhos nvarchar(100)  null,
Pcd nvarchar(100)  null,
Deficiencia nvarchar(100)  null,
Endereco nvarchar(100) null,
Numero nvarchar(25)  null,
Bairro nvarchar(100)  null,
Cidade nvarchar(100)  null,
Comple nvarchar(100)  null,
Cep nvarchar(10)  null,
Uf nvarchar(10) null,
Telefone nvarchar(100)  null,
Celular nvarchar(100)  null,
Departamento nvarchar(100)  null,
Cargo nvarchar(100)  not null,
Empresa nvarchar(30) null,
Adimissao nvarchar(12)  null,
Situacao nvarchar(15)  null,
Datacad  varchar(15)  null,
Supervisor nvarchar(100)  null,
Coordenador nvarchar(100) null,
Turno nvarchar(100)  null,
Fretado nvarchar(100)  null,
Obs nvarchar(1000)  null,
ImagemUrl nvarchar(250) null

)